import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import test from 'node:test';
const h=(q,r)=>({q,r}); const ship=(type,team,i,q,r)=>E.createShip(type,team,i,h(q,r));
function game(ships,extra={}){return {seed:1,round:1,map:{width:E.W,height:E.H,islands:[],mines:[]},ships,torpedoes:[],planes:[],nextId:0,log:[],winner:null,phase:'plan',...extra};}
const get=(g,id)=>g.ships.find(s=>s.id===id);
const quiet=s=>{delete s.cfg.secondary;delete s.cfg.aa;return s};
const forward=(n,turn=0)=>Array.from({length:n},()=>({turn,forward:true}));
function plane(m,id,pos,options={}){return {id,kind:'plane',team:m.team,mother:m.id,slot:0,hp:2,cfg:{...E.RULES.plane},xy:E.hexToXY(pos),mode:'point',target:pos,targetId:null,tracking:false,state:'outbound',traveled:0,waypoints:[],...options};}
test('default fleet exactly three front and two rear per team',()=>{const g=E.createGame();for(const team of [0,1]){const ss=g.ships.filter(s=>s.team===team);assert.equal(ss.length,5);assert.equal(ss.filter(s=>s.cfg.role==='front').length,3);assert.equal(ss.filter(s=>s.cfg.role==='back').length,2);}});
test('map deterministic mirror connected no blocked deployment 20 seeds',()=>{for(let seed=1;seed<=20;seed++){const m=E.generateMap(seed);assert.deepEqual(m,E.generateMap(seed));assert.equal(m.mines.length,8);for(const k of m.islands){const [q,r]=k.split(',').map(Number),c=E.toCR(h(q,r)).c;assert(m.islands.includes(E.key(E.fromCR(E.W-1-c,r))));}for(const d of [...E.deployment(0),...E.deployment(1)])assert(E.legal(m,d));const water=E.allHexes().filter(x=>E.legal(m,x)),seen=new Set([E.key(water[0])]),todo=[water[0]];for(const x of todo)for(let d=0;d<6;d++){const y=E.add(x,d);if(E.legal(m,y)&&!seen.has(E.key(y))){seen.add(E.key(y));todo.push(y)}}assert.equal(seen.size,water.length)}});
test('round deterministic and input unchanged',()=>{const a=quiet(ship('cl',0,0,0,5)),b=quiet(ship('cv',1,0,13,5)),g=game([a,b]);const p={[a.id]:{...E.emptyPlan(),moves:forward(3)}};const copy=E.clone(g);assert.deepEqual(E.resolveRound(g,p),E.resolveRound(g,p));assert.deepEqual(g,copy);});
test('team shares vision and islands block target LOS',()=>{const a=ship('cv',0,0,0,5),b=ship('cv',0,1,8,5),c=ship('cv',1,0,12,5),g=game([a,b,c]);assert(E.observe(g,0).ships.some(s=>s.id===c.id));g.map.islands=[E.key(h(10,5))];assert(!E.observe(g,0).ships.some(s=>s.id===c.id));});
test('hidden enemy changes cannot change AI plan',()=>{const a=ship('bb',0,0,0,5),c=ship('cv',1,0,12,5),g=game([a,c]),g2=E.clone(g);const e=get(g2,c.id);e.pos=h(14,7);e.xy=E.hexToXY(e.pos);e.hp=1;e.heading=0;assert.deepEqual(E.observe(g,0),E.observe(g2,0));assert.deepEqual(E.planAI(g,0),E.planAI(g2,0));});
test('turn costs step and no control zone stop',()=>{const a=quiet(ship('dd',0,0,3,5)),b=quiet(ship('cv',1,0,5,8)),g=game([a,b]);const p={...E.emptyPlan(),moves:[{turn:1,forward:false},...forward(3)]};const out=E.resolveRound(g,{[a.id]:p});assert.equal(get(out.game,a.id).heading,1);assert(E.same(get(out.game,a.id).pos,h(3,8)));});
test('torpedo one per window, three per round, broadside only and reserves',()=>{for(const kind of ['dd','cl']){const a=ship(kind,0,0,3,5),g=game([a]);const p={...E.emptyPlan(),moves:forward(a.cfg.speed),torps:[{window:0,dir:0},{window:0,dir:1},{window:0,dir:2},{window:1,dir:1},{window:2,dir:2},{window:3,dir:4}]};const v=E.validPlan(g,a,p);assert.equal(v.torps.length,3);assert.equal(new Set(v.torps.map(t=>t.window)).size,3);const r=E.resolveRound(g,{[a.id]:p});assert.equal(get(r.game,a.id).torps,kind==='dd'?0:6);assert.equal(r.events.filter(e=>e.text.includes('发射鱼雷')).length,3)}});
test('torpedo runs four hexes and expires after three rounds',()=>{const a=quiet(ship('dd',0,0,0,2)),b=quiet(ship('cv',1,0,14,12)),g=game([a,b]);let r=E.resolveRound(g,{[a.id]:{...E.emptyPlan(),torps:[{window:0,dir:1}]}});assert.equal(r.game.torpedoes.length,1);assert(E.same(E.xyToHex(r.game.torpedoes[0].xy),h(0,6)));r=E.resolveRound(r.game);assert.equal(r.game.torpedoes.length,1);assert(E.same(E.xyToHex(r.game.torpedoes[0].xy),h(0,10)));r=E.resolveRound(r.game);assert.equal(r.game.torpedoes.length,0);});
test('island blocks torpedo',()=>{const a=quiet(ship('dd',0,0,3,5)),b=quiet(ship('cv',1,0,4,9)),g=game([a,b]);g.map.islands=[E.key(h(3,7))];const r=E.resolveRound(g,{[a.id]:{...E.emptyPlan(),torps:[{window:0,dir:1}]}});assert.equal(r.game.torpedoes.length,0);assert.equal(get(r.game,b.id).hp,b.hp);});
test('CL single target vs CA once for each target',()=>{for(const type of ['cl','ca']){const a=ship(type,0,0,4,5),b=quiet(ship('cv',1,0,6,5)),c=quiet(ship('cv',1,1,4,7)),g=game([a,b,c]);const r=E.resolveRound(g);const damaged=[b,c].filter(s=>get(r.game,s.id).hp<s.hp);assert.equal(damaged.length,type==='cl'?1:2);for(const s of damaged)assert.equal(get(r.game,s.id).hp,s.hp-a.cfg.secondary.damage);}});
test('three stacked artillery shells hit end round; reload skips one round',()=>{const a=quiet(ship('bb',0,0,0,5)),b=quiet(ship('ca',1,0,5,5)),g=game([a,b]),p={...E.emptyPlan(),main:[b.pos,b.pos,b.pos]};let r=E.resolveRound(g,{[a.id]:p});assert.equal(r.frames[0].ships.find(s=>s.id===b.id).hp,b.hp);assert.equal(get(r.game,b.id).hp,50);assert.equal(E.validPlan(r.game,get(r.game,a.id),p).main.length,0);r=E.resolveRound(r.game);assert.equal(E.validPlan(r.game,get(r.game,a.id),p).main.length,3);});
test('remote sweep at start sacrifices all secondary but leaves main',()=>{const a=ship('bb',0,0,3,5),b=quiet(ship('ca',1,0,5,5)),g=game([a,b]);g.map.mines=[h(4,5)];const p={...E.emptyPlan(),sweep:h(4,5),main:[b.pos,b.pos,b.pos]},r=E.resolveRound(g,{[a.id]:p});assert.equal(r.frames[0].mines.length,0);assert.equal(get(r.game,b.id).hp,50);assert(!r.events.some(e=>e.text.includes('副炮命中')));});
test('DD contact sweep avoids mine damage',()=>{const a=quiet(ship('dd',0,0,3,5)),b=quiet(ship('cv',1,0,13,10)),g=game([a,b]);g.map.mines=[h(4,5)];const r=E.resolveRound(g,{[a.id]:{...E.emptyPlan(),moves:forward(1)}});assert.equal(get(r.game,a.id).hp,a.hp);assert.equal(r.game.map.mines.length,0);});
test('friendly collision hurts both, stops, cancels unreached torpedo windows and rolls back',()=>{const a=quiet(ship('dd',0,0,3,5)),b=quiet(ship('cl',0,1,5,5)),c=quiet(ship('cv',1,0,13,10)),g=game([a,b,c]);b.heading=3;const p={...E.emptyPlan(),moves:forward(5),torps:[{window:1,dir:1}]},r=E.resolveRound(g,{[a.id]:p,[b.id]:{...E.emptyPlan(),moves:forward(3)}});assert.equal(get(r.game,a.id).hp,80);assert.equal(get(r.game,b.id).hp,135);assert.equal(r.events.filter(e=>e.text.includes('发射鱼雷')).length,0);assert(E.same(get(r.game,a.id).pos,a.pos));assert(E.same(get(r.game,b.id).pos,b.pos));assert(r.events.some(e=>e.text.includes('沿原路回退')));});
test('aircraft HP2 speed6 vision3 no hidden target lock',()=>{const a=quiet(ship('cv',0,0,0,5)),b=quiet(ship('cv',1,0,13,5)),g=game([a,b]);assert.equal(E.validPlan(g,a,{...E.emptyPlan(),planes:[{mode:'target',targetId:b.id}]}).planes.length,0);const r=E.resolveRound(g,{[a.id]:{...E.emptyPlan(),planes:[{mode:'point',target:h(12,5)}]}});assert.equal(r.game.planes.length,1);const p=r.game.planes[0];assert.equal(p.hp,2);assert.equal(p.cfg.vision,3);assert(Math.abs(p.traveled-6)<1e-7);assert(E.same(E.xyToHex(p.xy),h(6,5)));});
test('point flight bombs first passed enemy; targeted flight ignores others',()=>{for(const mode of ['point','target']){const a=quiet(ship('cv',0,0,0,5)),b=quiet(ship('cv',1,0,2,5)),c=quiet(ship('cv',1,1,4,5)),g=game([a,b,c]);const order=mode==='point'?{mode,target:c.pos}:{mode,targetId:c.id};const r=E.resolveRound(g,{[a.id]:{...E.emptyPlan(),planes:[order]}});assert.equal(get(r.game,b.id).hp,b.hp-(mode==='point'?25:0));assert.equal(get(r.game,c.id).hp,c.hp-(mode==='target'?25:0));}});
test('AA removes HP2 before bomb damage',()=>{const a=quiet(ship('cv',0,0,0,5)),b=ship('dd',1,0,3,5),c=ship('cl',1,1,3,7),g=game([a,b,c]);const r=E.resolveRound(g,{[a.id]:{...E.emptyPlan(),planes:[{mode:'point',target:b.pos}]}});assert.equal(get(r.game,b.id).hp,b.hp);assert.equal(r.game.planes.length,0);assert.equal(get(r.game,a.id).destroyedPlanes,1);});
test('return plane follows moving mother and enters one-round rearm',()=>{const a=quiet(ship('cv',0,0,3,5)),b=quiet(ship('cv',1,0,13,10)),g=game([a,b]);a.airReady[0]=Infinity;g.planes=[plane(a,'p0',h(1,5),{state:'return'})];const r=E.resolveRound(g,{[a.id]:{...E.emptyPlan(),moves:forward(2)}});assert.equal(r.game.planes.length,0);assert.equal(get(r.game,a.id).airReady[0],3);assert.equal(get(r.game,a.id).destroyedPlanes,0);});
test('return plane mother already dead destroys plane',()=>{const a=quiet(ship('cv',0,0,3,5)),b=quiet(ship('cv',1,0,13,10)),g=game([a,b]);a.hp=0;g.planes=[plane(a,'p0',h(1,5),{state:'return'})];const r=E.resolveRound(g);assert.equal(r.game.planes.length,0);assert.equal(get(r.game,a.id).destroyedPlanes,1);});
test('round30 counts ship count before HP and excludes aircraft',()=>{const a=quiet(ship('dd',0,0,0,5)),b=quiet(ship('cv',0,1,0,12)),c=quiet(ship('bb',1,0,13,5)),g=game([a,b,c],{round:30});a.hp=1;b.hp=1;const r=E.resolveRound(g);assert.equal(r.game.winner,0);assert.equal(r.game.phase,'ended');});
test('aircraft12 is outbound only; return has its own distance and skips rearm round',()=>{const a=quiet(E.createShip('cv',0,0,E.fromCR(0,5))),b=quiet(E.createShip('cv',1,0,E.fromCR(18,14)));let g=game([a,b]);for(let i=0;i<4;i++){const r=E.resolveRound(g,i===0?{[a.id]:{...E.emptyPlan(),planes:[{mode:'point',target:E.fromCR(12,5)}]}}:{});g=r.game;if(i<2){assert.equal(g.planes.length,1);assert(Math.abs(g.planes[0].traveled-(i+1)*6)<1e-7);assert.equal(g.planes[0].state,i<1?'outbound':'return');}else if(i<3){assert.equal(g.planes.length,1);assert.equal(g.planes[0].state,'return');}}assert.equal(g.planes.length,0);assert.equal(get(g,a.id).airReady[0],6);});
test('carrier heals recovered aircraft once after rearm and preserves HP on relaunch',()=>{
 for(const [heal,expected] of [[0,1],[1,2],[10,4]]){
  const a=quiet(ship('cv',0,0,0,5)),b=quiet(ship('cv',1,0,13,12));
  a.cfg.carrier={...a.cfg.carrier,stock:1,heal,plane:{...a.cfg.carrier.plane,hp:4}};
  a.airReady=[Infinity];a.airHP=[4];
  let g=game([a,b]);g.planes=[plane(a,'p0',h(1,5),{hp:1,cfg:{...a.cfg.carrier.plane},state:'return'})];
  g=E.resolveRound(g).game;
  assert.equal(get(g,a.id).airHP[0],1,'recovery does not heal immediately');
  assert.equal(get(g,a.id).airReady[0],3);
  g=E.resolveRound(g).game;assert.equal(get(g,a.id).airHP[0],expected,'completed rearm heals by configured amount, capped at max');
  g=E.resolveRound(g).game;assert.equal(get(g,a.id).airHP[0],expected,'idle aircraft do not heal again');
  g=E.resolveRound(g,{[a.id]:{...E.emptyPlan(),planes:[{mode:'point',target:h(10,5)}]}}).game;
  assert.equal(g.planes.length,1);assert.equal(g.planes[0].hp,expected,'relaunch retains healed HP');
 }
});

test('AI starts in upper-right deployment while player stays lower-left',()=>{
 const g=E.createGame();
 for(const team of [0,1]){
  const zone=E.deployment(team);assert.equal(zone.length,9);
  for(const h of zone){const {c,r}=E.toCR(h);assert(team===0?c<3&&r>=E.H-3:c>=E.W-3&&r<3);}
  const ships=g.ships.filter(s=>s.team===team);assert.equal(new Set(ships.map(s=>E.key(s.pos))).size,5);
  for(const s of ships){assert(zone.some(h=>E.same(h,s.pos)));assert(E.legal(g.map,s.pos));assert(!g.map.mines.some(h=>E.same(h,s.pos)));}
 }
});
