import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {Window} from 'happy-dom';
const window=new Window({url:'http://localhost/'});
for(const k of ['window','document','navigator','HTMLElement','Element','SVGElement','Node','Event','MouseEvent','KeyboardEvent','MutationObserver','getComputedStyle','localStorage'])Object.defineProperty(globalThis,k,{value:k==='window'?window:typeof window[k]==='function'&&k==='getComputedStyle'?window[k].bind(window):window[k],configurable:true});
window.document.body.innerHTML='<div id="app"></div>';
const errors=[];const oldError=console.error;console.error=(...x)=>errors.push(x.join(' '));
let source=await fs.readFile(new URL('../src/main.js',import.meta.url),'utf8');
source=source.replace(/import\s+['"]\.\/style\.css['"];?\s*/,'').replace(/from\s+(['"])([^'"]+)\1/g,(_,quote,spec)=>'from '+JSON.stringify(spec.startsWith('./')?new URL('../src/'+spec.slice(2),import.meta.url).href:import.meta.resolve(spec)));
await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const wait=ms=>new Promise(r=>setTimeout(r,ms));const flush=async()=>{await Promise.resolve();await wait(0)};
const buttons=()=>[...document.querySelectorAll('button')];const button=(text)=>buttons().find(b=>b.textContent.replace(/\s/g,'').includes(text.replace(/\s/g,'')));const click=async el=>{assert.ok(el,'control exists');el.dispatchEvent(new window.MouseEvent('click',{bubbles:true}));await flush()};const hex=(c,r)=>document.querySelectorAll('polygon.hex')[r*19+c];
test('rendered Vue fleet → deploy → plan controls → complete round → restart',async()=>{
 await click(button('新游戏'));assert.match(document.body.textContent,/出击编队/);assert.equal(document.querySelectorAll('.roster-slot').length,5);
 await click(document.querySelectorAll('.roster-slot')[1]);await click([...document.querySelectorAll('.template-card')].find(x=>x.textContent.includes('驱逐')));assert.match(document.querySelectorAll('.roster-slot')[1].textContent,/驱逐/);
 await click(button('进入部署'));assert.match(document.body.textContent,/舰队部署/);assert.equal(document.querySelectorAll('polygon.hex').length,285);assert.equal(document.querySelectorAll('.ship-marker').length,5,'hidden enemy ships omitted');
 await click(hex(1,12));assert.match(document.querySelector('.ship-row-meta').textContent,/B13/);
 await click(button('完成部署'));assert.match(document.body.textContent,/战术规划/);
 await click(button('右转60'));await click(button('原地转向'));assert.equal(document.querySelectorAll('.action-item').length,1);assert.match(document.querySelector('.action-item').textContent,/右转/);
 await click(button('撤销末步'));assert.equal(document.querySelectorAll('.action-item').length,0);
 await click(button('鱼雷 T'));await click(hex(1,13));assert.equal(document.querySelectorAll('.action-item.torp').length,1);
 await click(document.querySelectorAll('.ship-row')[3]);await click(button('主炮 G'));const ownMarker=document.querySelectorAll('.ship-marker')[3];await click(ownMarker);await click(ownMarker);await click(ownMarker);assert.equal(document.querySelectorAll('.action-item.artillery').length,3,'marker receives repeated artillery selection');
 await click(button('清空'));assert.equal(document.querySelectorAll('.action-item.artillery').length,0);
 await click(document.querySelectorAll('.ship-row')[4]);await click(button('飞机 F'));await click(hex(9,7));await click(hex(10,7));assert.equal(document.querySelectorAll('.action-item.aviation').length,2);
 await click(button('执行回合'));await wait(900);await flush();assert.equal(errors.length,0,errors.join('\n'));assert.ok(button('跳过动画'));await click(button('跳过动画'));assert.match(document.querySelector('.round').textContent,/02/);assert.equal(document.querySelectorAll('.action-item').length,0,'plans cleared after resolution');assert.equal(errors.length,0,errors.join('\n'));
 await click(button('规则与操作'));assert.ok(document.querySelector('[role=dialog]'));await click(button('关闭'));await click(button('重新编队'));if(button('确认新游戏'))await click(button('确认新游戏'));assert.match(document.body.textContent,/出击编队/);
 await click(button('进入部署'));await click(button('完成部署'));await click(button('前进 W'));await click(button('右转60'));await click(button('重新编队'));if(button('确认新游戏'))await click(button('确认新游戏'));await click(button('进入部署'));await click(button('完成部署'));assert.ok(button('原地等待'),'new game clears pending turn');await click(button('鱼雷 T'));const windows=document.querySelector('.order-tool select');assert.equal(windows.value,'0','new game resets torpedo window');await click(hex(0,13));assert.equal(document.querySelectorAll('.action-item.torp').length,1,'new game initial window accepts torpedo');
});
