/* Pure deterministic simulation. Templates provide capabilities; roster tags never drive rules. */
export const W=19,H=15,DIRS=[[1,0],[0,1],[-1,1],[-1,0],[0,-1],[1,-1]];
export const RULES={roundLimit:30,ticks:240,shipRadius:Math.sqrt(3)/2-.001,mineDamage:40,torpedo:{speed:4,damage:45,life:3},plane:{hp:2,speed:6,vision:3,range:12,damage:25}};
const sec=(damage,range,multi=false)=>({damage,range,multi});
export const TEMPLATES={
 dd:{name:'驱逐',role:'front',hp:100,speed:4,vision:5,collision:15,secondary:sec(8,2),torpedo:{...RULES.torpedo,reserve:3,max:3},aa:{range:3,damage:1},contactSweep:true},
 cl:{name:'轻巡',role:'front',hp:150,speed:3,vision:5,collision:20,secondary:sec(12,3),torpedo:{...RULES.torpedo,reserve:9,max:3},aa:{range:2,damage:1}},
 ca:{name:'重巡',role:'front',hp:230,speed:3,vision:5,collision:30,secondary:sec(16,3,true),aa:{range:2,damage:1}},
 bb:{name:'战列',role:'back',hp:270,speed:2,vision:5,collision:35,secondary:sec(10,3),main:{range:9,shots:3,damage:60,reload:1},aa:{range:2,damage:1}},
 cv:{name:'航母',role:'back',hp:210,speed:2,vision:5,collision:15,carrier:{stock:6,launch:2,rearm:1,plane:{...RULES.plane}}}
};
export const DEFAULT_ROSTER=['dd','cl','ca','bb','cv'];
export const mod=(n,m=6)=>(n%m+m)%m;
export const clone=x=>structuredClone(x);
export const key=h=>`${h.q},${h.r}`;
export const fromCR=(c,r)=>({q:c-Math.floor(r/2),r});
export const toCR=h=>({c:h.q+Math.floor(h.r/2),r:h.r});
export const hexDist=(a,b)=>Math.max(Math.abs(a.q-b.q),Math.abs(a.r-b.r),Math.abs(a.q+a.r-b.q-b.r));
export const add=(h,d)=>({q:h.q+DIRS[mod(d)][0],r:h.r+DIRS[mod(d)][1]});
export const inBounds=h=>{const c=toCR(h);return c.c>=0&&c.c<W&&c.r>=0&&c.r<H};
export const hexToXY=h=>({x:Math.sqrt(3)*(h.q+h.r/2),y:1.5*h.r});
export function roundHex(q,r){let x=q,z=r,y=-x-z,rx=Math.round(x+1e-9),ry=Math.round(y+2e-9),rz=Math.round(z-3e-9);let dx=Math.abs(rx-x),dy=Math.abs(ry-y),dz=Math.abs(rz-z);if(dx>dy&&dx>dz)rx=-ry-rz;else if(dy>dz)ry=-rx-rz;else rz=-rx-ry;return {q:rx,r:rz};}
export const xyToHex=p=>roundHex(Math.sqrt(3)/3*p.x-p.y/3,2/3*p.y);
export const same=(a,b)=>a.q===b.q&&a.r===b.r;
export const allHexes=()=>Array.from({length:W*H},(_,i)=>fromCR(i%W,Math.floor(i/W)));
export function hexLine(a,b){const n=hexDist(a,b);return Array.from({length:n+1},(_,i)=>roundHex(a.q+(b.q-a.q)*i/(n||1),a.r+(b.r-a.r)*i/(n||1)));}
export function hasLOS(map,a,b){return hexLine(a,b).slice(1,-1).every(h=>!map.islands.includes(key(h)));}
export function legal(map,h){return inBounds(h)&&!map.islands.includes(key(h));}
export function deployment(team){return allHexes().filter(h=>{const {c,r}=toCR(h);return r>=H-3&&(team===0?c<3:c>=W-3)});}
function rng(seed){let a=(Number(seed)||1)>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
export function generateMap(seed=20261004){const rand=rng(seed),islands=new Set(),blocked=new Set([...deployment(0),...deployment(1)].map(key));const mirror=h=>{const {c,r}=toCR(h);return fromCR(W-1-c,r)};const connected=set=>{const water=allHexes().filter(h=>!set.has(key(h))),seen=new Set([key(water[0])]),q=[water[0]];for(let i=0;i<q.length;i++)for(let d=0;d<6;d++){const h=add(q[i],d),k=key(h);if(inBounds(h)&&!set.has(k)&&!seen.has(k)){seen.add(k);q.push(h)}}return seen.size===water.length};let anchor=fromCR(5,4);for(let n=0;islands.size<30&&n<3000;n++){if(n%4===0)anchor=fromCR(3+Math.floor(rand()*6),1+Math.floor(rand()*10));const h=n%4?add(anchor,Math.floor(rand()*6)):anchor,m=mirror(h);if(!inBounds(h)||h.r===5||h.r===10||blocked.has(key(h))||blocked.has(key(m)))continue;const trial=new Set([...islands,key(h),key(m)]);if(trial.size<=32&&connected(trial)){islands.add(key(h));islands.add(key(m));}}const mines=[];for(let n=0;mines.length<8&&n<1000;n++){const h=fromCR(3+Math.floor(rand()*6),1+Math.floor(rand()*12)),m=mirror(h);if(islands.has(key(h))||islands.has(key(m))||mines.some(x=>same(x,h)||same(x,m)))continue;mines.push(h,m);}return{width:W,height:H,islands:[...islands],mines};}
export function createShip(type,team,index,pos){const cfg={radius:RULES.shipRadius,...clone(TEMPLATES[type])};return{id:`${team}-${index}`,kind:'ship',team,label:`${cfg.name}-${index+1}`,template:type,cfg,hp:cfg.hp,pos:{...pos},xy:hexToXY(pos),heading:team===0?0:3,torps:cfg.torpedo?.reserve||0,mainReady:1,airReady:Array(cfg.carrier?.stock||0).fill(1),destroyedPlanes:0};}
export function createGame(roster=DEFAULT_ROSTER,seed=20261004){const map=generateMap(seed),spots=[0,2,4,6,8];const g={seed,round:1,map,ships:[...roster.map((t,i)=>createShip(t,0,i,deployment(0)[spots[i]])),...DEFAULT_ROSTER.map((t,i)=>createShip(t,1,i,deployment(1)[spots[4-i]]))],torpedoes:[],planes:[],nextId:0,log:[],winner:null,phase:'deploy',explored:[[],[]]};updateExploration(g);return g;}
export const alive=s=>s.hp>0;
export function visibleCells(g,team){const cells=new Set();const watchers=[...g.ships.filter(s=>s.team===team&&alive(s)).map(s=>({pos:xyToHex(s.xy),vision:s.cfg.vision})),...g.planes.filter(p=>p.team===team&&p.hp>0).map(p=>({pos:xyToHex(p.xy),vision:p.cfg.vision}))];for(const w of watchers)for(const h of allHexes())if(hexDist(w.pos,h)<=w.vision&&hasLOS(g.map,w.pos,h))cells.add(key(h));return cells;}
export function updateExploration(g){if(!g.explored)g.explored=[[],[]];for(const team of [0,1])g.explored[team]=[...new Set([...g.explored[team],...visibleCells(g,team)])];return g.explored;}
export function observe(g,team){const vis=visibleCells(g,team);return{round:g.round,map:{...clone(g.map),islands:g.explored?g.map.islands.filter(k=>g.explored[team].includes(k)):[...g.map.islands]},ships:g.ships.filter(s=>alive(s)&&(s.team===team||vis.has(key(xyToHex(s.xy))))).map(clone),torpedoes:g.torpedoes.filter(p=>p.team===team||vis.has(key(xyToHex(p.xy)))).map(clone),planes:g.planes.filter(p=>p.team===team||vis.has(key(xyToHex(p.xy)))).map(clone)};}
export const emptyPlan=()=>({moves:[],torps:[],main:[],planes:[],sweep:null});
export function route(ship,plan,map){let pos={...ship.pos},heading=ship.heading;const nodes=[{pos:{...pos},heading}];for(const move of (plan?.moves||[]).slice(0,ship.cfg.speed)){heading=mod(heading+Math.max(-1,Math.min(1,move.turn||0)));const next=move.forward?add(pos,heading):pos;if(move.forward&&!legal(map,next))break;pos={...next};nodes.push({pos:{...pos},heading});}return nodes;}
export function validPlan(g,s,p=emptyPlan()){const out=emptyPlan(),nodes=route(s,p,g.map);out.moves=(p.moves||[]).slice(0,nodes.length-1);const starts=visibleCells(g,s.team);const windows=new Set();for(const t of p.torps||[]){const n=nodes[t.window];if(!s.cfg.torpedo||!n||windows.has(t.window)||out.torps.length>=Math.min(s.torps,s.cfg.torpedo.max)||[n.heading,mod(n.heading+3)].includes(mod(t.dir))||t.window<0)continue;windows.add(t.window);out.torps.push({window:t.window,dir:mod(t.dir)});}if(s.cfg.main&&s.mainReady<=g.round)out.main=(p.main||[]).filter(h=>inBounds(h)&&hexDist(s.pos,h)<=s.cfg.main.range).slice(0,s.cfg.main.shots).map(clone);if(s.cfg.secondary&&p.sweep&&g.map.mines.some(h=>same(h,p.sweep))&&hexDist(s.pos,p.sweep)<=s.cfg.secondary.range&&hasLOS(g.map,s.pos,p.sweep))out.sweep=clone(p.sweep);if(s.cfg.carrier){const count=s.airReady.filter(n=>n<=g.round).length;out.planes=(p.planes||[]).filter(p=>p.mode==='point'?inBounds(p.target):g.ships.some(t=>t.id===p.targetId&&t.team!==s.team&&alive(t)&&starts.has(key(t.pos)))).slice(0,Math.min(s.cfg.carrier.launch,count)).map(clone);}return out;}
const length=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const lerp=(a,b,t)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});
const toward=(a,b,dist)=>{const l=length(a,b);return l<=dist?{...b}:lerp(a,b,dist/l)};
function collisionFraction(a,b,c,d,r){const px=a.x-c.x,py=a.y-c.y,vx=(b.x-a.x)-(d.x-c.x),vy=(b.y-a.y)-(d.y-c.y),C=px*px+py*py-r*r,A=vx*vx+vy*vy,B=2*(px*vx+py*vy);if(C<=1e-9)return 0;if(A<1e-12)return null;const disc=B*B-4*A*C;if(disc<0)return null;const t=(-B-Math.sqrt(disc))/(2*A);return t>=-1e-9&&t<=1+1e-9?Math.max(0,t):null;}
function frame(g,t,effects){return{t,ships:g.ships.filter(alive).map(s=>({id:s.id,team:s.team,label:s.label,hp:s.hp,cfg:s.cfg,pos:xyToHex(s.xy),xy:{...s.xy},heading:s.heading})),torpedoes:g.torpedoes.map(p=>({...p,xy:{...p.xy}})),planes:g.planes.filter(alive).map(p=>({...p,xy:{...p.xy}})),mines:clone(g.map.mines),visible:[...visibleCells(g,0)],explored:[...(g.explored?.[0]||[])],effects:effects.splice(0)};}
export function resolveRound(input,submitted={}){const g=clone(input),frames=[],events=[],effects=[],r=g.round;let time=0;const log=(text,at,team=null)=>{events.push({round:r,t:Number(time.toFixed(3)),text,at:at?clone(at):null,team});};const damage=(s,n,reason)=>{if(!alive(s))return;s.hp=Math.max(0,s.hp-n);effects.push({kind:'hit',at:xyToHex(s.xy),text:`−${n}`});log(`${s.label} ${reason} −${n}${s.hp===0?' · 沉没':''}`,xyToHex(s.xy),s.team)};const plans={},motion={},shots=[],collisionPairs=new Set(),secShots=new Map(),aaShots=new Set();
 for(const s of g.ships.filter(alive)){s.xy=hexToXY(s.pos);plans[s.id]=validPlan(g,s,submitted[s.id]);const p=plans[s.id];motion[s.id]={nodes:route(s,p,g.map),stopped:false,visited:[clone(s.pos)],fired:new Set()};}
 // Stable start: simultaneous sweep, launch artillery/aircraft, then initial torpedoes.
 const sweepKeys=new Set();for(const s of g.ships.filter(alive)){const p=plans[s.id];if(p.sweep){sweepKeys.add(key(p.sweep));log(`${s.label} 副炮清雷`,p.sweep,s.team);}if(p.main.length){for(const h of p.main)shots.push({at:h,damage:s.cfg.main.damage,team:s.team});s.mainReady=r+s.cfg.main.reload+1;log(`${s.label} 主炮发射 ${p.main.length} 发`,s.pos,s.team);}for(const order of p.planes){const slot=s.airReady.findIndex(n=>n<=r);if(slot<0)break;s.airReady[slot]=Infinity;const target=g.ships.find(t=>t.id===order.targetId);g.planes.push({id:`p${g.nextId++}`,kind:'plane',team:s.team,mother:s.id,slot,hp:s.cfg.carrier.plane.hp,cfg:clone(s.cfg.carrier.plane),xy:{...s.xy},mode:order.mode,target:clone(order.mode==='point'?order.target:target.pos),targetId:target?.id||null,tracking:order.mode==='target',state:'outbound',traveled:0,waypoints:[]});log(`${s.label} 放飞`,s.pos,s.team);}}
 g.map.mines=g.map.mines.filter(h=>!sweepKeys.has(key(h)));
 for(const p of g.planes){const target=g.ships.find(s=>s.id===p.targetId);p.tracking=!!(target&&alive(target)&&visibleCells(g,p.team).has(key(xyToHex(target.xy))));}
 const launchTorps=(s,window)=>{const m=motion[s.id];if(!m||m.fired.has(window)||!alive(s))return;m.fired.add(window);for(const o of plans[s.id].torps.filter(x=>x.window===window)){if(s.torps<=0)continue;s.torps--;g.torpedoes.push({id:`t${g.nextId++}`,kind:'torpedo',team:s.team,owner:s.id,xy:{...s.xy},heading:o.dir,age:0,launched:r,birth:time,armed:false,cfg:clone(s.cfg.torpedo)});log(`${s.label} 发射鱼雷`,xyToHex(s.xy),s.team);}};
 g.ships.filter(alive).forEach(s=>launchTorps(s,0));
 const returnPlane=p=>{p.state='return';p.waypoints=[];};
 const applyAA=()=>{const pending=[];for(const p of g.planes.filter(alive))for(const s of g.ships.filter(s=>alive(s)&&s.team!==p.team&&s.cfg.aa)){const k=`${s.id}:${p.id}`;if(!aaShots.has(k)&&hexDist(xyToHex(s.xy),xyToHex(p.xy))<=s.cfg.aa.range){aaShots.add(k);pending.push([p,s.cfg.aa.damage,s]);}}for(const [p,n,s]of pending){p.hp=Math.max(0,p.hp-n);effects.push({kind:'aa',from:xyToHex(s.xy),at:xyToHex(p.xy)});if(!p.hp)log(`${s.label} 击落敌机`,xyToHex(p.xy),s.team);}};
 const contacts=()=>{applyAA(); // Aircraft hit resolution must never precede AA at the same instant.
  const hits=[];for(const p of g.planes.filter(alive)){if(p.state==='return')continue;const h=xyToHex(p.xy);const target=g.ships.filter(s=>alive(s)&&s.team!==p.team&&same(xyToHex(s.xy),h)&&(p.mode!=='target'||s.id===p.targetId)).sort((a,b)=>a.id.localeCompare(b.id))[0];if(target){hits.push([target,p.cfg.damage,'遭航空炸弹命中']);returnPlane(p);}}
  for(const [s,n,why]of hits)damage(s,n,why);
  const deadT=new Set();for(const torp of g.torpedoes){const h=xyToHex(torp.xy),owner=g.ships.find(s=>s.id===torp.owner);if(!torp.armed&&(!owner||!same(h,xyToHex(owner.xy))))torp.armed=true;if(!inBounds(h)||g.map.islands.includes(key(h))){deadT.add(torp.id);continue;}if(!torp.armed)continue;const s=g.ships.filter(s=>alive(s)&&same(xyToHex(s.xy),h)).sort((a,b)=>a.id.localeCompare(b.id))[0];if(s){damage(s,torp.cfg.damage,'遭鱼雷命中');deadT.add(torp.id);}}
  g.torpedoes=g.torpedoes.filter(p=>!deadT.has(p.id));
  for(const mine of [...g.map.mines]){const targets=g.ships.filter(s=>alive(s)&&same(xyToHex(s.xy),mine)).sort((a,b)=>Number(!!b.cfg.contactSweep)-Number(!!a.cfg.contactSweep)||a.id.localeCompare(b.id));if(targets.length){const s=targets[0];g.map.mines=g.map.mines.filter(m=>!same(m,mine));if(s.cfg.contactSweep)log(`${s.label} 接触排雷`,mine,s.team);else damage(s,RULES.mineDamage,'触雷');}}
  const visibility=[visibleCells(g,0),visibleCells(g,1)],secondaryHits=[];for(const s of g.ships.filter(s=>alive(s)&&s.cfg.secondary&&!plans[s.id]?.sweep)){const fired=secShots.get(s.id)||new Set(),cfg=s.cfg.secondary;if(!cfg.multi&&fired.size)continue;const sh=xyToHex(s.xy),targets=g.ships.filter(t=>alive(t)&&t.team!==s.team&&!fired.has(t.id)&&visibility[s.team].has(key(xyToHex(t.xy)))&&hexDist(sh,xyToHex(t.xy))<=cfg.range&&hasLOS(g.map,sh,xyToHex(t.xy))).sort((a,b)=>hexDist(sh,xyToHex(a.xy))-hexDist(sh,xyToHex(b.xy))||a.id.localeCompare(b.id));for(const target of cfg.multi?targets:targets.slice(0,1)){fired.add(target.id);secondaryHits.push([target,cfg.damage,s]);}secShots.set(s.id,fired);}for(const[t,n,s]of secondaryHits){effects.push({kind:'shot',from:xyToHex(s.xy),at:xyToHex(t.xy)});damage(t,n,`遭${s.label}副炮命中`);}
 };
 contacts();updateExploration(g);frames.push(frame(g,0,effects));
 for(let tick=1;tick<=RULES.ticks;tick++){const prev=(tick-1)/RULES.ticks;time=tick/RULES.ticks;const dt=time-prev,candidates=new Map(),old=new Map();
  for(const s of g.ships.filter(alive)){old.set(s.id,{...s.xy});const m=motion[s.id];if(m.stopped){candidates.set(s.id,{...s.xy});continue;}const progress=time*s.cfg.speed,i=Math.min(Math.floor(progress+1e-9),s.cfg.speed),f=progress-i;const a=m.nodes[Math.min(i,m.nodes.length-1)],b=m.nodes[Math.min(i+1,m.nodes.length-1)];s.heading=(f>1e-9?b:a).heading;candidates.set(s.id,lerp(hexToXY(a.pos),hexToXY(b.pos),f));}
  // Swept circles avoid tunneling, including late impacts against stopped ships.
  const collisionHits=[],ships=g.ships.filter(alive),targets=new Map(candidates);let cursor=0,passes=0;
  while(passes++<ships.length*ships.length){
   const positionAt=(s,t)=>motion[s.id].stopped?candidates.get(s.id):lerp(old.get(s.id),targets.get(s.id),t),collisions=[];
   for(let i=0;i<ships.length;i++)for(let j=i+1;j<ships.length;j++){
    const a=ships[i],b=ships[j],pair=[a.id,b.id].sort().join('|');if(collisionPairs.has(pair))continue;
    const local=collisionFraction(positionAt(a,cursor),positionAt(a,1),positionAt(b,cursor),positionAt(b,1),a.cfg.radius+b.cfg.radius);
    if(local!==null)collisions.push({a,b,t:cursor+(1-cursor)*local,pair});
   }
   collisions.sort((a,b)=>a.t-b.t||a.pair.localeCompare(b.pair));if(!collisions.length)break;
   const first=collisions[0].t,group=collisions.filter(c=>Math.abs(c.t-first)<1e-7),points=new Map();
   for(const c of group)for(const ship of [c.a,c.b])if(!points.has(ship.id))points.set(ship.id,{...positionAt(ship,first)});
   for(const c of group){collisionPairs.add(c.pair);collisionHits.push([c.a,c.b.cfg.collision],[c.b,c.a.cfg.collision]);}
   for(const [id,p] of points){candidates.set(id,p);motion[id].stopped=true;}
   cursor=first;
  }
  for(const s of ships){s.xy=candidates.get(s.id);const m=motion[s.id];if(!m.stopped){const count=Math.floor(time*s.cfg.speed+1e-8),was=Math.floor(prev*s.cfg.speed+1e-8);for(let i=was+1;i<=count&&i<m.nodes.length;i++){m.visited.push(clone(m.nodes[i].pos));launchTorps(s,i);}}}
  for(const t of g.torpedoes){if(t.birth===time&&t.launched===r)continue;const v=hexToXY({q:DIRS[t.heading][0],r:DIRS[t.heading][1]});t.xy.x+=v.x*t.cfg.speed*dt;t.xy.y+=v.y*t.cfg.speed*dt;t.age+=dt;}
  for(const p of g.planes.filter(alive)){const mother=g.ships.find(s=>s.id===p.mother);if(p.state==='return'&&(!mother||!alive(mother))){p.hp=0;log('返航飞机失去母舰',xyToHex(p.xy),p.team);continue;}let target;
   if(p.state==='return')target=mother.xy;else if(p.mode==='target'){const s=g.ships.find(s=>s.id===p.targetId);if(!s||!alive(s)){returnPlane(p);target=mother?.xy||p.xy;}else{if(!p.tracking&&visibleCells(g,p.team).has(key(xyToHex(s.xy))))p.tracking=true;if(p.tracking)p.target=xyToHex(s.xy);target=p.tracking?s.xy:hexToXY(p.target);}}else target=hexToXY(p.target);
   const before={...p.xy},budget=p.state==='outbound'?Math.max(0,p.cfg.range-p.traveled):Infinity,step=Math.min(p.cfg.speed*dt,budget)*Math.sqrt(3);p.xy=toward(p.xy,target,step);if(p.state==='outbound')p.traveled+=length(before,p.xy)/Math.sqrt(3);
  }
  applyAA();for(const [s,n] of collisionHits)damage(s,n,'发生碰撞');contacts();
  for(const p of g.planes.filter(alive)){const mother=g.ships.find(s=>s.id===p.mother);if(p.state==='outbound'&&(p.traveled>=p.cfg.range-1e-8||p.mode==='point'&&length(p.xy,hexToXY(p.target))<1e-7||p.mode==='target'&&!p.tracking&&length(p.xy,hexToXY(p.target))<1e-7))returnPlane(p);if(p.state==='return'&&mother&&alive(mother)&&length(p.xy,mother.xy)<.12){mother.airReady[p.slot]=r+mother.cfg.carrier.rearm+1;p.hp=0;p.recovered=true;log(`${mother.label} 回收飞机`,xyToHex(mother.xy),p.team);}}
  for(const p of g.planes.filter(p=>!alive(p)&&!p.accounted)){const m=g.ships.find(s=>s.id===p.mother);if(m&&!p.recovered)m.destroyedPlanes++;p.accounted=true;}
  g.planes=g.planes.filter(alive);g.torpedoes=g.torpedoes.filter(t=>t.age<t.cfg.life-1e-8);
  updateExploration(g);if(tick%8===0)frames.push(frame(g,time,effects));
 }
 // All committed shells arrive even if their firing ship has sunk.
 const mainHits=new Map();for(const shot of shots){effects.push({kind:'main',at:shot.at});for(const s of g.ships.filter(s=>alive(s)&&same(xyToHex(s.xy),shot.at)))mainHits.set(s.id,(mainHits.get(s.id)||0)+shot.damage);}for(const[id,n]of mainHits)damage(g.ships.find(s=>s.id===id),n,'遭主炮命中');
 const occupied=new Set();const stopped=g.ships.filter(s=>alive(s)&&motion[s.id].stopped);for(const s of g.ships.filter(s=>alive(s)&&!motion[s.id].stopped)){s.pos=xyToHex(s.xy);s.xy=hexToXY(s.pos);occupied.add(key(s.pos));}
 // Alternating initiative is reproducible and shares rollback priority between teams.
 stopped.sort((a,b)=>(a.team===r%2?-1:1)-(b.team===r%2?-1:1)||a.id.localeCompare(b.id));for(const s of stopped){const candidates=[...motion[s.id].visited].reverse();const h=candidates.find(h=>legal(g.map,h)&&!occupied.has(key(h)));if(h){s.pos=clone(h);s.xy=hexToXY(h);occupied.add(key(h));log(`${s.label} 沿原路回退`,h,s.team);}else{damage(s,s.hp,'碰撞搁浅');}}
 for(const p of g.planes){const mother=g.ships.find(s=>s.id===p.mother);if(p.state==='return'&&(!mother||!alive(mother))){p.hp=0;if(mother&&!p.accounted)mother.destroyedPlanes++;p.accounted=true;log('返航飞机失去母舰',xyToHex(p.xy),p.team);}}
 g.planes=g.planes.filter(alive);
 for(const p of g.planes){const t=g.ships.find(s=>s.id===p.targetId);if(t&&p.tracking)p.target=clone(xyToHex(t.xy));p.tracking=false;}
 updateExploration(g);frames.push(frame(g,1.1,effects));g.log=[...g.log,...events].slice(-300);const counts=[0,1].map(team=>{const ss=g.ships.filter(s=>s.team===team&&alive(s));return{count:ss.length,hp:ss.reduce((n,s)=>n+s.hp,0)}});if(!counts[0].count||!counts[1].count||r>=RULES.roundLimit){g.winner=counts[0].count===counts[1].count?(counts[0].hp===counts[1].hp?'draw':counts[0].hp>counts[1].hp?0:1):counts[0].count>counts[1].count?0:1;g.phase='ended';}else{g.round++;g.phase='plan';}return{game:g,frames,events,counts};}
function navigationDistances(map,goal,range=0){const distances=new Map(),queue=[];const k=(h,d)=>`${key(h)}:${d}`;for(const h of allHexes())if(legal(map,h)&&hexDist(h,goal)===range&&hasLOS(map,h,goal))for(let d=0;d<6;d++){distances.set(k(h,d),0);queue.push({h,d});}if(!queue.length)for(let d=0;d<6;d++){distances.set(k(goal,d),0);queue.push({h:goal,d});}for(let i=0;i<queue.length;i++){const {h,d}=queue[i],cost=distances.get(k(h,d))+1;for(const turn of[-1,0,1])for(const forward of[true,false]){const previous=forward?add(h,mod(d+3)):h,hd=mod(d-turn),id=k(previous,hd);if(legal(map,previous)&&!distances.has(id)){distances.set(id,cost);queue.push({h:previous,d:hd});}}}return distances;}
export function planAI(game,team){const v=observe(game,team),friends=v.ships.filter(s=>s.team===team),enemies=v.ships.filter(s=>s.team!==team),plans={},reserved=[];for(const s of friends.sort((a,b)=>b.cfg.speed-a.cfg.speed||a.id.localeCompare(b.id))){const p=emptyPlan();let at=clone(s.pos),heading=s.heading;const preferred=s.cfg.carrier?7:s.cfg.main?6:s.cfg.secondary?.range||2;const target=enemies.slice().sort((a,b)=>hexDist(at,a.pos)-hexDist(at,b.pos)||a.id.localeCompare(b.id))[0];const searchPoints=team===0?[[16,12],[14,5],[9,2],[3,6]]:[[2,12],[4,5],[9,2],[15,6]],search=searchPoints[Math.floor((v.round-1)/5)%searchPoints.length],goal=target?.pos||fromCR(search[0],Math.min(14,search[1]+Number(s.id.split('-')[1])%3)),navigation=navigationDistances(v.map,goal,target?preferred:0);for(let n=0;n<s.cfg.speed;n++){let best=null;for(const turn of[-1,0,1])for(const forward of[true,false]){const hd=mod(heading+turn),h=forward?add(at,hd):at;if(!legal(v.map,h))continue;let score=-(navigation.get(`${key(h)}:${hd}`)??100)*2.5+(forward?.1:0)-Math.abs(turn)*.06;if(v.map.mines.some(m=>same(m,h))&&!s.cfg.contactSweep)score-=12;for(const f of friends)if(f.id!==s.id&&hexDist(h,f.pos)<1)score-=10;for(const r of reserved)if(hexDist(h,r)<1)score-=15;for(const torp of v.torpedoes){const th=xyToHex(torp.xy);for(let k=0;k<3;k++)if(same(h,{q:th.q+DIRS[torp.heading][0]*k,r:th.r+DIRS[torp.heading][1]*k}))score-=8;}if(!best||score>best.score)best={turn,forward,h,hd,score};}if(!best)break;p.moves.push({turn:best.turn,forward:best.forward});at=best.h;heading=best.hd;}reserved.push(at);const nodes=route(s,p,v.map);if(s.cfg.torpedo&&s.torps&&enemies.length){const options=[];for(let w=0;w<nodes.length;w++)for(let d=0;d<6;d++){if([nodes[w].heading,mod(nodes[w].heading+3)].includes(d))continue;let h=nodes[w].pos,score=0;for(let k=1;k<=10;k++){h=add(h,d);if(!legal(v.map,h))break;if(friends.some(f=>f.id!==s.id&&same(f.pos,h)))score-=20;for(const enemy of enemies){if(same(enemy.pos,h))score+=12/(1+k*.1);const prediction=add(enemy.pos,enemy.heading);if(same(prediction,h))score+=6;}}if(score>3)options.push({window:w,dir:d,score});}options.sort((a,b)=>b.score-a.score);for(const o of options)if(!p.torps.some(t=>t.window===o.window)&&p.torps.length<Math.min(s.torps,s.cfg.torpedo.max))p.torps.push(o);}
 if(s.cfg.main&&s.mainReady<=v.round){const targets=enemies.filter(e=>hexDist(s.pos,e.pos)<=s.cfg.main.range);if(targets.length){const e=targets.sort((a,b)=>a.hp-b.hp)[0],pred=add(e.pos,e.heading);p.main=[clone(e.pos),clone(legal(v.map,pred)&&hexDist(s.pos,pred)<=s.cfg.main.range?pred:e.pos),clone(e.pos)];}}
 if(s.cfg.carrier){const ready=Math.min(s.cfg.carrier.launch,s.airReady.filter(x=>x<=v.round).length);for(let i=0;i<ready;i++){if(target)p.planes.push({mode:'target',targetId:target.id});else p.planes.push({mode:'point',target:fromCR(team===0?13:5,5+(Number(s.id.split('-')[1])+i*3)%8)});}}
 if(s.cfg.secondary){const mine=v.map.mines.find(m=>hexDist(s.pos,m)<=s.cfg.secondary.range&&hasLOS(v.map,s.pos,m)&&nodes.some(n=>hexDist(n.pos,m)<=1));if(mine&&!s.cfg.contactSweep)p.sweep=clone(mine);}plans[s.id]=validPlan(game,s,p);}return plans;}
